[profile.default]
src = "src"
out = "out"
libs = ["./dependencies"]
ffi = true

[dependencies]
forge-std = "1.9.4"
"@openzeppelin-contracts" = "5.1.0"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
